-- MySQL Script generated by MySQL Workbench
-- Thu 02 Nov 2023 09:47:05 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bchydro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bchydro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bchydro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bchydro` ;

-- -----------------------------------------------------
-- Table `accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` VARCHAR(16) NOT NULL COMMENT 'The account ID. String.',
  `name` VARCHAR(45) NULL DEFAULT NULL COMMENT 'The name of the account owner.',
  `description` LONGTEXT NULL DEFAULT NULL COMMENT 'Short description of this account.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `usage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usage` (
  `id` VARCHAR(20) NOT NULL COMMENT 'The account ID ',
  `timestamp` DATETIME NOT NULL COMMENT 'The timestamp of the usage data point in local time (Pacific).',
  `usage` DECIMAL(10,4) NOT NULL COMMENT 'The usage in kilowatt hours.',
  PRIMARY KEY (`id`, `timestamp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

